### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by tmzr** [eliksir/screenie-server#12]
Hi,
Install don't work for me on windows seven with node.js 8.9.4 LTS and 9.5.0 Current.
npm install screenie-server
C:\temp>npm install screenie-server
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tmeziere\AppData\Roaming\npm-cache\_logs\2018-02-13T20_27_
21_463Z-debug.log
[2018-02-13T20_27_21_463Z-debug.log](https://github.com/eliksir/screenie-server/files/1721609/2018-02-13T20_27_21_463Z-debug.log)

I'm relatively newbie on Node.js, maybe I've misunderstand something...
I've tried to install dependencies individually and launch server.js
C:\temp>node server.js
2018-02-13T21:07:17.817Z - info: Screenie server started on port 3000
2018-02-13T21:08:29.345Z - error: instance.process is not a function
2018-02-13T21:08:29.567Z - error: instance.process is not a function
but get an internal server error at  http://localhost:3000/?url=http://google.com/&format=jpeg

Kind regards

**Comment by fdanielsen** [comment]
Hi @tmzr! Thanks for your report. We haven't tested this on Windows ourselves and have no plans in the near future to do that as we don't develop on that platform. But both of these issues you're experiencing seem to be about your environment and not the package itself.

The first issue is simply that you don't have the source control system git installed, which is required to install npm dependencies from GitHub (we have a custom fork of a dependency for now). So you'll need to install git to properly install this package from npm.

The second error refers to the `process` property of a puppeteer browser instance not being a function, which it should be according to puppeteer's API. So it is hard to say why the puppeteer instance is different on Windows for you.

I'm sorry but I'm going to close this since we don't have the resources to debug on Windows as of now. I would suggest you try to run our Docker-version which would run it within a known and tested Linux container. Or, if you do have the time to look deeper into this yourself we would of course welcome any PRs that improves Windows support.

**Comment by tmzr** [comment]
Thanks for feedback.
I'll try to solved my config.
