### ISSUE TITLE
Babel issue when running in docker

### ISSUE THREAD

**Issue by omerzach** [eliksir/screenie-server#2]
Hey, I'm trying to run screenie-server in a docker container but having some trouble related to ES6 syntax. Any idea how to solve this? Some Googling suggests adding `require("babel-register")` might help?

https://gist.github.com/omerzach/001421c268cd37b416e3d70de8451607

**Comment by asteinlein** [comment]
Hi Omer! Not sure about that error, but we already have a Docker image you should be able to use: https://hub.docker.com/r/eliksir/screenie-server/

Let me know if it doesn't work for you or you have any questions.

**Comment by omerzach** [comment]
Even better, will give that a try 👍

**Comment by fdanielsen** [comment]
Hi Omer! The error is because we use some ES6 syntax that requires a newer version of node, in part because we use the Koa HTTP server. As the package.json states we require version 6 or higher of node. You could be able to run it on older node if you run node with the `--harmony` flag, but I won't guarantee it. From your gist I assume you're running v4.8 which is the only official Docker image of node tagged with argon.

But as Anders said, if you use our own Docker image for this you'll be good, it uses node v7 :)

**Comment by omerzach** [comment]
I got it working using your Docker image. Thanks for the help!
